baseurl = "https://coderade.github.io"
languageCode = "en-us"
title = "Coderade blog"
# Define how many pages appear per site
paginate = 10
enableemoji = true
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "coderade"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-106618202-1"
theme = "coderade-minimalist-theme"
publishdir = "coderade.github.io"
[params]
    site_author = "Valdeci Gomes"
    site_description = "The awesome blog of Valdeci Gomes, about code, technology and tips in general."
    location = "Curitiba, PR, Brazil"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/puralsight-bg.jpg"
    baseurl="https://valde.ci/"
    header_title = "<Coding, DevOps and Software Engineering tips/>"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = ["css/theme.css"]
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-106618202-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    linkedin  = "valdeci/en"
    behance   = ""
    dribbble  = ""
    github    = "coderade"
    goodreads = "valdeci"
    stackoverflow = "4157589"
    stackexchange = "5196485"
    gplus     = ""

[blackfriday]
  hrefTargetBlank = true
