baseurl = "https://coderade.github.io/"
languageCode = "en-us"
title = "Coderade blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "coderade"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
publishdir = "coderade.github.io"
[params]
    site_author = "Valdeci Gomes"
    site_description = "The awesome blog of Valdeci Gomes, about code, technology and tips in general."
    location = "Curitiba, PR, Brazil"
    # Link custom assets relative to /static
    avatar = "img/profile-image.jpg"
    header_background = "img/puralsight-bg.jpg"
    header_title = "Coding, Life Hacks and tips in general"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = ["css/theme.css"]
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "valdessai"
    facebook  = "valdessai"
    linkedin  = "valdeci/en"
    behance   = ""
    dribbble  = ""
    instagram = "valdessai"
    github    = "coderade"
    gplus     = ""